security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
        - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    encoders:
        App\Entity\User: bcrypt

    providers:
        users:
            id: App\Security\UserProvider

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # -> custom firewall for the admin area of the URL
        admin:
            pattern: ^/
            form_login:
                default_target_path: /
                provider:       users
                login_path:     /
                use_forward:    false
                check_path:     /login_check
                success_handler: app.security.authentication_handler
                failure_handler: app.security.authentication_handler
            logout:
                path:           admin_logout
                target:         /
            anonymous:          true
            json_login:
                check_path: /login_check
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
        main:
            form_login:
                default_target_path: /
                provider:       users
                login_path:     /
                use_forward:    false
                check_path:     admin_login
                failure_path:   null
                success_handler: app.security.authentication_handler
                failure_handler: app.security.authentication_handler
            logout:
                path:           admin_logout
                target:         /
            anonymous:          true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000 # 30 days. Default is one year
                path:     /

    access_control:
    - { path: ^/login$, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/register, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
    - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
    - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
