sonata_admin:
    assets:
        extra_stylesheets:
            - bundles/sonatamultiupload/dist/sonata-multiupload.css
            - https://rawgit.com/enyo/dropzone/master/dist/dropzone.css

        extra_javascripts:
            - bundles/sonatamultiupload/dist/sonata-multiupload.js
            - https://rawgit.com/enyo/dropzone/master/dist/dropzone.js